/**
 * \file TestFieldmapVsAnalytic.cpp
 * \brief The FIELDMAP element against the analytic element it was built from.
 *
 * Build a field map that reproduces a MULTIPOLE exactly, then check that a FIELDMAP driven by
 * that map gives the same field as the MULTIPOLE itself, on the host and on the device.
 *
 * MULTIPOLE is the right reference for this. Its field is constant for a dipole and affine in
 * each coordinate for a quadrupole (Multipole::computeField), so trilinear interpolation
 * reproduces it with zero discretisation error: the grid spacing drops out of the tolerance
 * budget completely, and the comparison sits at round-off. It is also a straight box with a
 * hard edge and no fringe. RBEND was rejected because it carries an Enge fringe and divides by
 * a reference charge that defaults to 1 with no bunch attached; CORRECTOR because its field is
 * ramped over one time step at each end, so it depends on dt and is not tabulatable at all.
 *
 * The map is generated by sampling the element itself rather than by re-deriving its formula,
 * so the generator cannot drift from what Multipole actually does, and every parse-time
 * scaling convention -- the P0/c factor, the factor of two on the dipole component -- is
 * bypassed because the Rep is driven directly.
 */

#include "AbsBeamline/FieldmapElement.h"
#include "BeamlineCore/FieldmapElementRep.h"
#include "BeamlineCore/MultipoleRep.h"
#include "BeamlineGeometry/Geometry.h"
#include "Fields/Fieldmap.h"
#include "Ippl.h"
#include "PartBunch/BunchStateHandler.h"
#include "PartBunch/ParticleContainer.hpp"

#include "gtest/gtest.h"

extern Inform* gmsg;

#include <algorithm>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <string>
#include <vector>

namespace {

    /// Grid covering the element, in mm. z spans exactly [0, L] so the map's window and the
    /// multipole's hard edge coincide; x and y reach a full cell past every sampled point,
    /// because the last grid plane in each axis has no cell to interpolate in.
    struct Grid {
        double x0 = -40.0, y0 = -40.0, z0 = 0.0;
        double dx = 10.0, dy = 10.0, dz = 5.0;
        int nx = 9, ny = 9, nz = 41;  // z: 0 .. 200 mm = L

        double xAt(int i) const { return x0 + i * dx; }
        double yAt(int i) const { return y0 + i * dy; }
        double zAt(int i) const { return z0 + i * dz; }
    };

    constexpr double kLength = 0.200;  // m, must equal (nz - 1) * dz / 1000

    /// Sample an element on the grid and write the result as a G4beamline `grid` map.
    void writeMapFromElement(const std::string& path, ElementBase& element, const Grid& g) {
        std::ofstream f(path);
        f << "param normB=1. current=1.\n";
        f << "grid X0=" << g.x0 << " Y0=" << g.y0 << " Z0=" << g.z0 << " nX=" << g.nx
          << " nY=" << g.ny << " nZ=" << g.nz << " dX=" << g.dx << " dY=" << g.dy << " dZ=" << g.dz
          << "\n";
        f << "data\n";
        f << std::setprecision(17);

        const Vector_t<double, 3> P(0.0);
        for (int ix = 0; ix < g.nx; ++ix) {
            for (int iy = 0; iy < g.ny; ++iy) {
                for (int iz = 0; iz < g.nz; ++iz) {
                    const double xmm = g.xAt(ix), ymm = g.yAt(iy), zmm = g.zAt(iz);
                    // Multipole's field stops just before z = L, so the last plane is
                    // sampled just inside the exit. The map still records it at z = L.
                    const double z = std::min(zmm * 1e-3, std::nextafter(kLength, 0.0));
                    const Vector_t<double, 3> R(xmm * 1e-3, ymm * 1e-3, z);
                    Vector_t<double, 3> E(0.0), B(0.0);
                    element.apply(R, P, 0.0, E, B);
                    f << xmm << " " << ymm << " " << zmm << " " << B(0) << " " << B(1) << " "
                      << B(2) << "\n";
                }
            }
        }
    }

}  // namespace

class FieldmapVsAnalyticTest : public ::testing::Test {
protected:
    static void SetUpTestSuite() {
        int argc    = 0;
        char** argv = nullptr;
        ippl::initialize(argc, argv);
        gmsg = new Inform(nullptr, -1);
        std::filesystem::create_directories("data");
    }

    static void TearDownTestSuite() {
        delete gmsg;
        gmsg = nullptr;
        ippl::finalize();
    }

    void SetUp() override {
        const auto* info = ::testing::UnitTest::GetInstance()->current_test_info();
        mapFile_         = std::string("data/fmvsanalytic_") + info->name() + ".g4blmap";
    }

    void TearDown() override {
        Fieldmap::freeMap(mapFile_);
        std::filesystem::remove(mapFile_);
    }

    /// A multipole with one normal component, wide open transversely.
    static std::shared_ptr<MultipoleRep> makeMultipole(int order, double value) {
        auto mp = std::make_shared<MultipoleRep>("ANALYTIC");
        mp->getGeometry().setElementLength(kLength);
        mp->setNormalComponent(order, value);
        mp->setAperture(ApertureType::ELLIPTICAL, {1.0, 1.0});
        return mp;
    }

    /// A FIELDMAP on the given map file, with the same wide-open aperture.
    std::shared_ptr<FieldmapElementRep> makeFieldmapElement() {
        auto fm = std::make_shared<FieldmapElementRep>("FROM_MAP");
        fm->setFieldMapFN(mapFile_);
        fm->setAperture(ApertureType::ELLIPTICAL, {1.0, 1.0});
        fm->initialise(nullptr);
        Fieldmap::readMap(mapFile_);
        return fm;
    }

    /// Interior sample points, deliberately off the grid nodes.
    static std::vector<Vector_t<double, 3>> samplePoints() {
        std::vector<Vector_t<double, 3>> points;
        for (int i = 0; i < 11; ++i) {
            for (int j = 0; j < 11; ++j) {
                for (int k = 0; k < 9; ++k) {
                    // x, y within [-0.035, 0.035]; z strictly inside (0, L).
                    points.emplace_back(
                            -0.035 + i * 0.007 + 0.0013, -0.035 + j * 0.007 - 0.0011,
                            0.002 + k * 0.0245 + 0.0007);
                }
            }
        }
        return points;
    }

    /// Compare the two elements' host field at every sample point.
    void expectSameHostField(ElementBase& analytic, ElementBase& fromMap, double tolerance) {
        const Vector_t<double, 3> P(0.0);
        for (const auto& R : samplePoints()) {
            Vector_t<double, 3> Ea(0.0), Ba(0.0), Ef(0.0), Bf(0.0);
            analytic.apply(R, P, 0.0, Ea, Ba);
            fromMap.apply(R, P, 0.0, Ef, Bf);

            for (unsigned d = 0; d < 3; ++d) {
                ASSERT_NEAR(Ba(d), Bf(d), tolerance) << "component " << d << " at (" << R(0) << ", "
                                                     << R(1) << ", " << R(2) << ")";
            }
        }
    }

    std::string mapFile_;
};

// A dipole is a constant field, so the map holds one repeated value and interpolation is
// trivially exact.
TEST_F(FieldmapVsAnalyticTest, DipoleMatchesToRoundOff) {
    auto mp = makeMultipole(0, 0.35);
    Grid g;
    writeMapFromElement(mapFile_, *mp, g);

    auto fm = makeFieldmapElement();
    EXPECT_NEAR(fm->getGeometry().getElementLength(), kLength, 1e-12);

    expectSameHostField(*mp, *fm, 1e-12);
}

// A quadrupole is affine in each coordinate: Bx = k*y, By = k*x. Trilinear interpolation
// reproduces that exactly too, so the tolerance stays at round-off.
TEST_F(FieldmapVsAnalyticTest, QuadrupoleMatchesToRoundOff) {
    auto mp = makeMultipole(1, 2.5);
    Grid g;
    writeMapFromElement(mapFile_, *mp, g);

    auto fm = makeFieldmapElement();
    expectSameHostField(*mp, *fm, 1e-12);

    // Sanity: the field is not trivially zero, so the comparison above means something.
    const Vector_t<double, 3> R(0.02, 0.01, 0.1);
    const Vector_t<double, 3> P(0.0);
    Vector_t<double, 3> E(0.0), B(0.0);
    mp->apply(R, P, 0.0, E, B);
    EXPECT_GT(std::abs(B(0)) + std::abs(B(1)), 1e-3);
}

// With a correct implementation, a coarse grid must give the SAME answer, because the field
// is multilinear. Asserting the round-off tolerance on 3 x 3 x 5 points is a much stronger
// statement than agreeing to 1e-3 on a fine grid.
TEST_F(FieldmapVsAnalyticTest, CoarseGridIsJustAsExact) {
    auto mp = makeMultipole(1, 2.5);

    Grid g;
    g.nx = 3;
    g.ny = 3;
    g.nz = 5;
    g.dx = 40.0;
    g.dy = 40.0;
    g.dz = 50.0;  // 4 * 50 = 200 mm = L
    g.x0 = -40.0;
    g.y0 = -40.0;
    writeMapFromElement(mapFile_, *mp, g);

    auto fm = makeFieldmapElement();
    expectSameHostField(*mp, *fm, 1e-12);
}

// The same comparison through the Kokkos path both elements use during tracking.
TEST_F(FieldmapVsAnalyticTest, DeviceFieldMatchesToRoundOff) {
    auto mp = makeMultipole(1, 2.5);
    Grid g;
    writeMapFromElement(mapFile_, *mp, g);
    auto fm = makeFieldmapElement();

    const auto points = samplePoints();
    const size_t n    = points.size();

    const Vector_t<int, 3> nr(8);
    const Vector_t<double, 3> rmin(-1.0);
    const Vector_t<double, 3> hr(0.25);
    ippl::NDIndex<3> domain;
    for (unsigned d = 0; d < 3; ++d) {
        domain[d] = ippl::Index(nr[d]);
    }
    std::array<bool, 3> decomp{true, true, true};
    ippl::UniformCartesian<double, 3> mesh(domain, hr, rmin);
    ippl::FieldLayout<3> layout(MPI_COMM_WORLD, domain, decomp, false);

    auto pc = std::make_shared<ParticleContainer_t>(mesh, layout);
    pc->setBunchStateHandler(std::make_shared<BunchStateHandler>());
    pc->allocateParticles(n);
    pc->createParticles(n);

    auto R     = pc->R.getView();
    auto B     = pc->B.getView();
    auto hostR = Kokkos::create_mirror_view(R);
    for (size_t i = 0; i < n; ++i) {
        hostR(i) = points[i];
    }
    Kokkos::deep_copy(R, hostR);

    auto zeroB = Kokkos::create_mirror_view(B);
    for (size_t i = 0; i < n; ++i) {
        zeroB(i) = Vector_t<double, 3>(0.0);
    }

    Kokkos::deep_copy(B, zeroB);
    mp->apply(pc);
    Kokkos::fence();
    auto analyticB = Kokkos::create_mirror_view(B);
    Kokkos::deep_copy(analyticB, B);

    Kokkos::deep_copy(B, zeroB);
    fm->apply(pc);
    Kokkos::fence();
    auto mapB = Kokkos::create_mirror_view(B);
    Kokkos::deep_copy(mapB, B);

    for (size_t i = 0; i < n; ++i) {
        for (unsigned d = 0; d < 3; ++d) {
            ASSERT_NEAR(analyticB(i)(d), mapB(i)(d), 1e-12)
                    << "particle " << i << " component " << d;
        }
    }
}
